name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.5
  retrofit: ^4.1.0
  gap: ^3.0.1
  flutter_secure_storage: ^9.2.2
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  drift: ^2.15.0
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.21
  path_provider: ^2.1.3
  path: ^1.8.3
  dio: ^5.4.3+1
  http: ^1.2.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  retrofit_generator: ^8.1.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/league.png
    - assets/standings.png